apiVersion: v1
kind: Service
metadata:
  name: matias-service-clusterip
spec:
  selector:
    app: myapp-api
    type: back-end
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP