version: '3.8'
services:
  movie-analyst-api:
    image: gauch0/r-api
    environment:
      - DB_HOST=${myip}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    container_name: api
    ports:
      - '3000:3000'
  
  movie-analyst-ui:
    image: gauch0/r-ui
    environment:
      - BACKEND_URL=${myip}:3000
    container_name: ui
    ports:
      - '80:8000'
    depends_on:
      - movie-analyst-api

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    container_name: bbdd
    ports:
      - '3306:3306'
    volumes:
      - ./scheme.sql:/docker-entrypoint-initdb.d/scheme.sql
    depends_on:
      - movie-analyst-api
      - movie-analyst-ui