apiVersion: v1
kind: Service
metadata:
  name: matias-service-loadbalancer
spec:
  selector:
      app: myapp-ui
      type: front-end
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer