name: AWS-Terraform-github-actions

on:
  push:
    branches: [ main ]


jobs:
  jobs_terraform_version:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Verificar la version de terraform
       run: terraform --version 








# jobs:
#   job_1-setup-credentials:
#     runs-on: ubuntu-latest
#       steps:
#       - name: Setup Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         env:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

# jobs:
#   build:
#     name: Emulate build step
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checking out repository
#       uses: actions/checkout@v2
#     - name: "Upload artifacts"
#       uses: actions/upload-artifact@v2
#       with:
#         name: build-artifacts
#         path: ${{ github.workspace }}/resources


  # job_2-terraform-actions-vpc:
  #   runs-on: ubuntu-latest
  #   needs: job_1-setup-credentials
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Terraform Init
  #     working-directory: AWSDocker/vpc
  #     run: |
  #       ls -lha
  #       terraform init
  
  # job_3-terraform-actions-ec2:
  #   runs-on: ubuntu-latest
  #   needs: job_1-setup-credentials
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Terraform Init
  #     working-directory: AWSDocker/ec2
  #     run: |
  #       ls -lha
  #       terraform init
  
  # job_4-terraform-apply-vpc:
  #   runs-on: ubuntu-latest
  #   needs: job_2-terraform-actions-vpc
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: terraform apply
  #     working-directory: AWSDocker/vpc
  #     run:
  #       terraform apply -auto-approve
  
  # job_5-terraform-apply-ec2:
  #   runs-on: ubuntu-latest
  #   needs: job_2-terraform-actions-vpc
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: terraform apply
  #     working-directory: AWSDocker/ec2
  #     run:
  #       terraform apply -auto-approve