name: AWS-Terraform-github-actions

on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID : ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY : ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  jobs_terraform_version:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Verificar la version de terraform
       run: terraform --version 
  
  jobs_terraform_init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Inicializa terraform en VPC
      working-directory: AWSDocker/vpc
      run: terraform init